# material mining speed multipliers
#   | none | wood | stone | iron | diamond | netherite | gold |
#   |    1 |    2 |     4 |    6 |       8 |         9 |   12 |

# inhib mining speed multipliers
#   | none | wood | stone | iron | diamond | netherite | gold |
#   |      | 0.25 |   0.5 | 0.75 |     1.0 |     1.125 |  1.5 |

kits:
  BASIC:
    items:
      - item: 'wooden_sword'
      - item: 'wooden_pickaxe[tool={rules:[{speed:2,correct_for_drops:true,blocks:"#mineable/pickaxe"},{speed:0.2,correct_for_drops:true,blocks:"white_stained_glass"}]}]'
      # - item: 'stone_pickaxe[tool={rules:[{speed:4,correct_for_drops:true,blocks:"#mineable/pickaxe"},{speed:0.3,correct_for_drops:true,blocks:"white_stained_glass"}]}]'
      # - item: 'iron_pickaxe[tool={rules:[{speed:6,correct_for_drops:true,blocks:"#mineable/pickaxe"},{speed:0.4,correct_for_drops:true,blocks:"white_stained_glass"}]}]'
      # - item: 'diamond_pickaxe[tool={rules:[{speed:6,correct_for_drops:true,blocks:"#mineable/pickaxe"},{speed:0.6,correct_for_drops:true,blocks:"white_stained_glass"}]}]'
  SANTAS_FAVORITE:
    items:
      - item: coal
        count: 32
      - item: stone
        count: 21
